### ISSUE TITLE
add siemens_to_ismrmrd

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#1]
will need to add https://github.com/ismrmrd/siemens_to_ismrmrd to the VM. can be done via the update_VM.sh

**Comment by KrisThielemans** [comment]
Add `siemens_to_ismrmrd` to superbuild, but not its dependencies. Introduce option to build it, defaults to YES only if other dependencies are present. Install extra dependencies on the VM.

**Comment by paskino** [comment]
closed with #46
