### ISSUE TITLE
Desktop Manager

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/CCPPETMR_VM#10]
We need an alternative manager. Considerations:

- image size
    - perhaps switch base image to Ubuntu Server Edition
- user friendliness
    - ubuntu-gnome-desktop (1.5GB)
    - MATE (>2GB)
    - lxde (<1GB?)
    - i3 (<2MB) + base a desktop env for the daemons

**Comment by NikEfth** [comment]
Hi,

just for the completeness of the discussion :) :


  * image size
      o perhaps switch base image to Ubuntu Server Edition
  * user friendliness
      o ubuntu-gnome-desktop (1.5GB)
      o MATE (>2GB)
      o lxde (<1GB?)
      o i3 (<2MB) + base a desktop env for the daemons.

**Comment by KrisThielemans** [comment]
I think with our recent additions of a few Gnome utilities, the current system is fine. It's probably most future proof as Ubuntu is moving to Gnome3 as default anyway. So I'm going to close this issue. Sorry to those who like other options better.

PS: note that we're already based on Ubuntu-server
