### ISSUE TITLE
Build on Linux without system ACE will fail

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/CCPPETMR_VM#102]
Currently the `UPDATE.sh` script relies on the presence of ACE as system library. While this is ok for current Ubuntu, it is not the case for Scientific Linux or similar. 

Since [27th June](https://github.com/CCPPETMR/SIRF-SuperBuild/commit/b16e1499107de97650d9c3c90cc3603dd54d0306) SuperBuild has the option to build its own ACE. 

I see 2 options to fix this
1. `UPDATE.sh` accepts another argument which will set `USE_SYSTEM_ACE=ON/OFF`
2. Have the SuperBuild check whether ACE is found and if not to set `USE_SYSTEM_ACE=OFF`

**Comment by KrisThielemans** [comment]
I prefer the second option. Let's close it once https://github.com/CCPPETMR/SIRF-SuperBuild/issues/156 is closed.
