### ISSUE TITLE
locale issues

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#11]
lots of things (including gnome-terminal) don't work if locale isn't set.

The following solved it 
```
sudo locale-gen
localectl set-locale LANG="en_GB.UTF-8"
```
but there might be some issue with using en_GB of the gnome Region and Languages control panel hasn't been used yet to set to UK.

@casperdcl  recommends
```
localedef -v -c -i en_GB -f UTF-8 en_GB.UTF-8
```
at VM creation time.

**Comment by paskino** [comment]
it seems fixed with a less bare gnome.

**Comment by casperdcl** [comment]
Ok, just for future ref I'd amend my recommendation to: `sudo apt-get install locales && locale-gen en_GB.UTF-8`
