### ISSUE TITLE
move install shell script in Vagrantfile to a standalone script

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/CCPPETMR_VM#114]
using `config.vm.provision "shell", inline: <<-SHELL` at [this ](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile#L93) line works fine but the content of the `shell` script should go into a standalone script that can be used to configure a different VM as Jenkins or Travis.

**Comment by KrisThielemans** [comment]
sure, could put it in `devel/CCPPETMR_VM/scripts/`. Note that it is debian-specific.

This is of course https://github.com/CCPPETMR/SIRF-SuperBuild/issues/91
