### ISSUE TITLE
update_VM_to_full_STIR.sh broken

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#120]
https://github.com/CCPPETMR/CCPPETMR_VM/blob/4cf8c9f149e288ffb36844b51ba8ba658d87d53f/scripts/update_VM_to_full_STIR.sh#L20

is wrong. Need to go to whereever it's being build.

**Comment by rijobro** [comment]
close via c30d2b8a3182268a1d28cd401d18d40239811cc6
