### ISSUE TITLE
jupyter port forwarding doc

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#123]
The starting the jupyter server in the VM and connecting to it via your own "host" browser does work:
```
jupyter notebook --no-browser --ip 0.0.0.0
```
on the host, connect to `http://localhost:8888/?token=....` (where the token needs to be copied from the terminal).

However, it is not documented. I think this needs to be on https://github.com/CCPPETMR/CCPPETMR_VM/wiki/Getting-started-with-SIRF, and pointed to this at https://github.com/CCPPETMR/SIRF-Exercises. I think it'd be best to have a tiny script for this (`start_jupyter.sh`?). (side note: adding that script now will get it to people after an `update_VM.sh`)

Also, when connecting to `http://localhost:8888` it asks for a password (or the token). @paskino, what is the password? As far as I can see, it's safe to put this on the web the port should only be visible on the host.

**Comment by paskino** [comment]
consider also #117

**Comment by paskino** [comment]
on `first_run.sh` execution one should add the following config 

```
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.notebook_dir = u'/home/sirfuser/devel/SIRF-Exercises/notebooks'
```

with this + default password (virtual), starting jupyter notebook can be done from a terminal in any directory as `jupyter notebook`

**Comment by paskino** [comment]
I added documentation on the wiki regarding starting jupyter notebook.
