### ISSUE TITLE
sudo no longer asks for password on 18.02 VM

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#128]
Not 100% sure if this is a bad thing (@casperdcl ?) but it's unexpected.

**Comment by casperdcl** [comment]
don't know about VM but I'm pretty sure I gave the docker image users passwordless sudo permissions. Should be fine since

1. it's a VM/container
2. you don't allow passwordless ssh access

**Comment by KrisThielemans** [comment]
ok. closing
