### ISSUE TITLE
need to document how to change keyboard

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#14]
Click on “Activities”, type “settings” -> Region and Languages, use add_input and select UK (or whatever is appropriate for you)

**Comment by paskino** [comment]
I believe that we may refer to the standard Ubuntu way, as the VM is a standard Ubuntu machine with Gnome3.

**Comment by KrisThielemans** [comment]
sure. but it needs to be written somewhere (maybe with a link, or very brief description)
