### ISSUE TITLE
/home/sirfuser/.cache/pip is owned by root

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#140]
seems we need a `chmod -R` in the `Vagrantfile`

**Comment by rijobro** [comment]
seems ok https://github.com/CCPPETMR/CCPPETMR_VM/blob/c4dc2613582e8a4d79ffab51d95562b9ae7a5bf1/scripts/bootstrap_ubuntu.sh#L81
