### ISSUE TITLE
need to add optical drive to the VM

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#15]
best for Guest Additions. Instructions: 

Shutdown machine, then go to VB interface, click the VM, then Settings, Storage, click the left most icon next to the IDE controller, (add optical drive). Choose "Leave empty".

**Comment by paskino** [comment]
done

**Comment by KrisThielemans** [comment]
ideally we do this via vagrant later (if possible at all) to avoid manual steps.

**Comment by KrisThielemans** [comment]
https://groups.google.com/forum/#!topic/vagrant-up/Z_KruTTN0vk seems to imply
```
vb.customize "pre-boot", [
       "storageattach", :id,
       "--storagectl", "IDE Controller",
        "--port", "1",
       "--device", "0",
       "--type", "dvddrive",
       "--medium", "emptydrive",
       ]
```

**Comment by paskino** [comment]
closed by https://github.com/CCPPETMR/CCPPETMR_VM/commit/904280602e710dad48d2c42752befe48e4837bfd
