### ISSUE TITLE
Make complete set of installation instructions

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#17]
Current README.md has instructons on vagrant but we still need a lot of other steps to be performed afterwards. Can we list them (and later automate this as much as possible)? If we need a lot of stops, I'd move this from README.md to a new file, maybe CREATE.md?

**Comment by paskino** [comment]
[] vagrant user
[] cdrom

**Comment by KrisThielemans** [comment]
cdrom: see #15 

Also need to document
```
sudo dd if=/dev/zero of=/EMPTY bs=1M
sudo rm -f /EMPTY
```
before export.

**Comment by KrisThielemans** [comment]
vagrant user: what about adding the following in the SHELL bit
```
sed -e 's/SystemAccount=.*/SystemAccount=true/' /var/lib/AccountsService/users/vagrant > /tmp/vagrant.user
mv /tmp/vagrant.user /var/lib/AccountsService/users/vagrant
```

**Comment by KrisThielemans** [comment]
See also #20  and #19.

For all the stuff that needs to be run as sirfuser, we could create a script e.g. `VM_first_run.sh` (or something better). It would do the gnome stuff, 'UPDATE.sh'. Anything else?
Our instructions could then be:
1. VM_first_run.sh
2. sudo VM_zero_disk.sh
3. sudo shutdown -h now

Or of course all of this could be in a script as well...

**Comment by paskino** [comment]
I believe that we are currently left with manually running just the zerofill trick.

**Comment by KrisThielemans** [comment]
great work!

The zerofill, #19 and #20 cannot be done from the Vagrantfile, so let's just make the script(s) as I suggested above.

**Comment by paskino** [comment]
possibly closed with https://github.com/CCPPETMR/CCPPETMR_VM/commit/077f2eab4cb21566b61646f2f6f7ef153a1fa99d

**Comment by KrisThielemans** [comment]
perfect. does it need to run as `sudo`? If not, feel free to close

**Comment by paskino** [comment]
No, it changes the gnome settings for the `sirfuser` and the zerofill trick writes to somewhere we can.
