### ISSUE TITLE
disable screen lock

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#19]
screen lock doesn't make sense on a VM and is annoying. 
```
gsettings set org.gnome.desktop.screensaver lock-enabled true
```
would do it, but how to run this as sirfuser from the Vagrantfile?

**Comment by paskino** [comment]
It is possible to run it from the vagrantfile, however it won't work as gsettings expects a gnome-session to be active.

**Comment by KrisThielemans** [comment]
minor annoynace anyway and user can change this
