### ISSUE TITLE
enlarge pointer size

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#20]
The pointer size is too small in my opinion. The following should help
```
sudo apt-get install dmz-cursor-theme 
gsettings set org.gnome.desktop.interface cursor-size 120
```
It is only effective at the next log-in but that's ok.

The sudo statement needs to go in the Vagrantfile.

**Comment by paskino** [comment]
same comment as #19

**Comment by KrisThielemans** [comment]
cannot be done at VM creation due to problems running `gsettings` without running Gnome desktop for sirfuser. In any case, specific to certain displays.

**Comment by paskino** [comment]
could be added to the first_run script

**Comment by KrisThielemans** [comment]
sure. unless I'm the only one who suffers from it :-;

**Comment by paskino** [comment]
it's easy enough now.
