### ISSUE TITLE
apt-get upgrade hangs on grub

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#21]
Attempting an upgrade gives a screen with "configuring grub-pc" and no way to get out of it apparently.
(If you try this, make a snapshot first!)
![virtualbox_sirf_vm_devel_27_05_2017_23_00_20](https://cloud.githubusercontent.com/assets/6362141/26524599/87ae950a-4330-11e7-9d81-f747e592e549.png)
Killing it leads to problems with dpkg later.

**Comment by paskino** [comment]
Won't pushing tab highlight the <OK>?

It has worked on my VM.

**Comment by KrisThielemans** [comment]
indeed it does. amazing.

next hurdle was then what (and how) to answer. I use /dev/sda as suggested [here](https://askubuntu.com/questions/23418/what-do-i-select-for-grub-install-devices-after-an-update) but I still need to verify if that worked. what nonsense though.

of course, we cannot have this for the non-attended VM. I'm not 100% sure what the best solution is.

- either put the upgrade in the Vagrantfile with some extra stuff as in https://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt

- or do the upgrade manually in the VM.

I'd be fine with the 2nd option (as long as we mention it explicitly in our list of steps). Possibly our linux experts @casperdcl and @bathomas  have an opinion here...

**Comment by casperdcl** [comment]
Hi,

My view is that dist-upgrades should be done at the Vagrantfile/VM creation
stage, whereas plain upgrades should work within the VM when run by the end
user at any time.

If ubuntu/virtualbox needs some configuring/fixing to allow the latter then
I'd vote to put those fixes in the vagrantfile too.

Regards,
Casper

**Comment by casperdcl** [comment]
Ah just saw the rest of the issue... Looks like we may need

```
export DEBIAN_FRONTEND=noninteractive
```
?

**Comment by casperdcl** [comment]
I'd be surprised if dist-upgrades and anything which messes with grub is meant to work in a VM. grub (bootloader) is likely to confuse itself upgrading as it doesn't know it's in a VM

**Comment by KrisThielemans** [comment]
I agree with dist-upgrades (i.e. we don't want it). This is happening with "just" a normal upgrade (maybe because how the box was constructed). I do think we need to prepare the VM to be ready for a user that does an upgrade.

**Comment by KrisThielemans** [comment]
done manually for 0.9.0

**Comment by paskino** [comment]
As a workaround  
`apt-mark hold grub-pc`
in https://github.com/CCPPETMR/CCPPETMR_VM/commit/f0e1bdcc08b908d12258f3093e596d02c0078546
 closes this issue.
