### ISSUE TITLE
user-friendly editor for VM

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/CCPPETMR_VM#23]
VM does not seem to have a user-friendly editor. Suggest adding

sudo apt-get install leafpad

to UPDATE.sh

**Comment by KrisThielemans** [comment]
we cannot add apt-get install commands to UPDATE.sh. we could add it to "prerequisites". I don't think leafpad is the one of choice for most ubuntu people though (it is for Lubuntu). could add gedit if it doesn't add a lot of other packages.

Note that you can use spyder for editing of course, so we could just recommend that if there are large space consequences.

**Comment by KrisThielemans** [comment]
Let's use `nano`. Set git variable
```
export GIT_EDITOR=nano
```
probably
```
export EDITOR=nano
```

**Comment by KrisThielemans** [comment]
now done in `UPDATE.sh`
