### ISSUE TITLE
name of VM needs to reflect the version number

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#24]
The current VM is called v0.9.0-rc2. the final one needs to remove the rc suffix.

Possibly this can be automated (later) via the vagrantfile

**Comment by KrisThielemans** [comment]
Done manually for 0.9.0

**Comment by KrisThielemans** [comment]
This might work in the VirtualBox section
```
  # Provide a name to the VM
   vb.name = "CCPPETMR_VM"
```
but we'd need to provide the version number somehow

**Comment by paskino** [comment]
closed with https://github.com/CCPPETMR/CCPPETMR_VM/commit/f0e1bdcc08b908d12258f3093e596d02c0078546
