### ISSUE TITLE
switch update_VM.sh to use the SuperBuild

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#25]
Although the current update_VM.sh is relatively simple, it is not good to rely on 2 separate build mechanisms, especially for version tracking.

**Comment by paskino** [comment]
I will delete the binaries in the VM built with the old update scripts when running the superbuild. Any objections?

**Comment by KrisThielemans** [comment]
somewhat dangerous? Maybe just write a warning at the end (and in an email) and recommend to delete them.

**Comment by paskino** [comment]
If I do not delete the directory devel/build I will have to build the SIRF-SuperBuild in the source directory.
