### ISSUE TITLE
update mechanism with superbuild is stuck at SIRF et al versions

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#31]
See https://github.com/CCPPETMR/SIRF-SuperBuild/issues/51

suggested solution: remove cached TAGs and URLs in `UPDATE.sh` such that defaults will work
```
cmake -U '*_TAG' -U '*_URL' .
```
I think it is reasonable for people to expect that an update will reset their configuration, as long as it is documented. If they don't want that, they can just `git pull` and run CMake themselves.

By the way, with this suggestion, `DEVEL_BUILD` will still remain as cached, which I think is reasonable as well.

**Comment by paskino** [comment]
The obvious other option is to delete the cache.

**Comment by KrisThielemans** [comment]
a complete delete will mean rebuilding everything. painful...

**Comment by KrisThielemans** [comment]
@paskino can you please test the suggested approach and commit?
