### ISSUE TITLE
install in better place

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#35]
As suggested in https://github.com/CCPPETMR/SIRF-SuperBuild/issues/16, use
```
cmake -DCMAKE_INSTALL_PREFIX=${SIRF_SRC_PATH}/install
```
it's then easier for us/the user to clean up the build files.

**Comment by paskino** [comment]
Done https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L84
