### ISSUE TITLE
data folder duplication on VM 

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/CCPPETMR_VM#42]
I have added some files to data/examples/PET, and on VM they ended up in ~/devel/SIRF-SuperBuild/SIRF/examples/Python/PET. But demo scripts look for the data in /devel/buildVM/SIRF/examples/Python/PET, which has not received those files. How can the two folders be kept synchronized (and why do we have this duplication anyway)?

**Comment by KrisThielemans** [comment]
I'm confused. the demo script should look in subdirs of `pet_data_path`, which should be set to whereever the git clone was (not the build). there is no duplication.

**Comment by evgueni-ovtchinnikov** [comment]
I looked at my VMs and I am now even more confused than you, Kris.

I found one VM on which SIRF-SuperBuild does not even have subfolder SIRF - but that VM is likely to be just imported and not updated.

On another VM, SIRF-SuperBuild has subfolder SIRF, but it is empty, all SIRF sources and data are in ~/devel/buildVM/SIRF.

On all others both SIRF-SuperBuild/SIRF and buildVM/SIRF contain SIRF sources and data (and that is the duplication I pointed at), but the former is either on master or devel branch, whereas the latter has HEAD detached at v0.9.2 (which explains why it does not have updated data).

The value of SIRF_PATH (which is used by pet_data_path) is ~/devel/buildVM/SIRF.

**Comment by KrisThielemans** [comment]
right. we're all confused. great! :-)

The danger with the VMs obviously is that you have too many, and that they are in various stages of our development.

Currently, the VM update mechanism will run the superbuild in `~/devel/buildVM` (as "binary directory", the sources are in `~/devel/SIRF-SuperBuild`. It will then clone SIRF in `~/devel/buildVM/SIRF`, and then checkout to whatever tag is in `~/devel/SIRF-SuperBuild/version_config.cmake` unless you force this to something else by running CMake.

The fact that in one of your VMs you have a `SIRF-SuperBuild/SIRF` means that it's old. If you update it, it will ignore the content of that directory.

hope that makes some sense.

There's is therefore no duplication if you'd get a new VM, or clear up some stuff and update again.

Please close if I'm correct...

**Comment by evgueni-ovtchinnikov** [comment]
So, if I want to update SIRF only, I need to git pull in buildVM/SIRF?

Just tried, and all seems well, so closing the issue.
