### ISSUE TITLE
xenial64 creation fails

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/CCPPETMR_VM#44]
https://github.com/CCPPETMR/CCPPETMR_VM/commit/fa0fd2ccc0aeb126a2d89c3f98cd5cb93e7054fd

The VM gets created but UPDATE.sh fails miserably at line 38.

**Comment by KrisThielemans** [comment]
Please copy error message. It worked for me.
________________________________

**Comment by paskino** [comment]
While running `UPDATE.sh` this is the output message. 
 
`An error occurred in /home/sirfuser/devel/CCPPETMR_VM/scripts/UPDATE.sh at line 38. Current working-dir: /home/sirfuser/devel/CCPPETMR_VM`

I've created 3 VMs with xenial. The first one seems to have worked and I fixed the parameters of the vagrant script. When I later tried to create a VM from the `Vagrantfile` it has lead both times to the previous error.

**Comment by paskino** [comment]
The error message claims the problem being at [this line](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L38).

However, I've commented out lines [30](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L30 ) and [32](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L32) (which were meant to give a sensible error message) and the build process started)

**Comment by paskino** [comment]
I've now rebuilt a VM from scratch with the [xenial64 branch](https://github.com/CCPPETMR/CCPPETMR_VM/tree/xenial64) in which I commented out lines [30](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L30 ) and [32](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L32).

It builds correctly. Tests are positive.

**Comment by KrisThielemans** [comment]
I see you reinstated them which makes me happy. I'd be reluctant to remove all error checking. of course, as opposed to a global catch-all, we could do it for every statement, but that's a bit more tedious...

The `grep` line 
```sh
 added=`grep -c "source ~/.sirfrc" ~/.bashrc`
```
could create trouble when there is no `~/.bashrc' possibly. (I'd have to read-up on what `set -e` does with lines like that). can be checked by doing this with a non-existing file and printing `$?`. If that's the cause, then you could resolve this by putting the following first
```sh
touch .bashrc
```
which will create a file if it didn't exist (and just update its timestamp if it did)

**Comment by paskino** [comment]
it seems the culprit is `grep -c`. I do not understand why bash traps an error on that line. Is there any?
 
I've put back the `gawk` command I came with some time ago and with that it seems to work.

**Comment by paskino** [comment]
Closed with https://github.com/CCPPETMR/CCPPETMR_VM/commit/cd74e32359e660edd5274a46c0f95a91062bc3f8
