### ISSUE TITLE
current VM has user ubuntu

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#48]
after a `vagrant up` I have both vagrant and sirfuser.

if too hard to fix in the `vagrantfile`, can remove the user manually before shipping.

**Comment by paskino** [comment]
Is that true? I've got a Ubuntu user, which I don't manage to remove with the trick we used before!

**Comment by KrisThielemans** [comment]
yes it's true :-;
at least on my windows version with an "vagrant box upgrade" (recommended to get the latest ubuntu).

let's just say that you remove the user after VM creation (add it to our list of steps, and then shift this to 1.1)

**Comment by paskino** [comment]
amazing

**Comment by KrisThielemans** [comment]
so, I had a `vagrant` user because I was building on trusty. Now when using xenial as I should have, I indeed also have a user `ubuntu`.

**Comment by paskino** [comment]
I can remove the Ubuntu user manually from the VM if needed.

**Comment by KrisThielemans** [comment]
I guess I'd do that in the final one yes. Minimal confusion is good. add it to the checklist :-;

I suppose you tried this in the vagrant script
```
sudo deluser --remove-home ubuntu
```

**Comment by paskino** [comment]
closed by #64
