### ISSUE TITLE
Disk sizes

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/CCPPETMR_VM#5]
Support/make less painful custom/resizing disk, c.f.:

- [resizing-virtual-drive](https://askubuntu.com/questions/101715/resizing-virtual-drive)
- [increase-HD-size-VM](https://askubuntu.com/questions/88647/how-do-i-increase-the-hard-disk-size-of-the-virtual-machine)

**Comment by paskino** [comment]
I think this should be closed by now.
