### ISSUE TITLE
updating SIRF_VM_VERSION?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#50]
I don't think [UPDATE.sh](scripts/UPDATE.sh) currently will update the stored version in an existing VM. It's not clear if this is desired or not (arguably, the VM is the old, but after it's updated, it's almost equivalent to the new one...).

This might be confusing...

In any case, at present it will be set to 0.9

**Comment by paskino** [comment]
AFAIK, it does write the [`.sirf_VM_version=0.9.2`](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L208).
I will add a version file in the CCPPETMR_VM repository with states the version of the VM and we pick the version up from that file.
