### ISSUE TITLE
keyboard issues

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#53]
we attempt to set it to UK in the Vagrantfile
```
sudo localectl set-x11-keymap uk
```
but it seems to still be US. In fact, I cannot see any of the other languages that we try to add in the Vagrantfile...

In any case, we need to make the text in our [INSTALL.md](INSTALL.md) consistent with the actual situation. (It currently mentions 3 languages, and a keyboard icon on the top-right, but that is not there right now as no other language is installed).

**Comment by paskino** [comment]
Yes, I believe that the button we refer to is a property of the gnome-panel. Because we can't change it from the vagrant file that won't appear.

**Comment by paskino** [comment]
closed by #63
