### ISSUE TITLE
copy HELP.txt to Desktop

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#54]
any chance we can do this? At present, the user starts this and gets a completely blank screen.

This turns out to be hard though. [See here](https://elementaryos.stackexchange.com/questions/9/why-cant-i-place-files-on-the-desktop-by-default-and-how-can-i-get-this-featur) for some discussion.

**Comment by paskino** [comment]
It is done [here](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/UPDATE.sh#L194). I guess that's a Desktop environment problem.

**Comment by KrisThielemans** [comment]
closing as not possible in Gnome
