### ISSUE TITLE
problem adding Guest Additions CD

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#59]
On a Mac, I select the Devices menu option "Insert Guest Additions CD image ...". In the bottom right of the VM, a drive symbol turns blue and the tooltip suggests it is an .iso file within the  /Applications folder on the Mac.

Running the update_VGS.sh script gives error "Failed to find VBox Guest Additions CD". The /media/sirfuser folder on the VM appears to be empty.

Is there a mount step missing?

**Comment by paskino** [comment]
yes, I guess so

**Comment by KrisThielemans** [comment]
This should have been fixed by 349bd2e4b498d4e18cabf69a9b9b844ad97b3460. @DANAJK, please reopen if not.
