### ISSUE TITLE
create a first run script?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#63]
seems that the amount of manual steps is increasing again, e.g. #48, all the Gnome stuff such as #53, the zerofill trick.

What about creating a script that contains all these steps? Then we can run only that manually. (Could even by really fancy and somehow make it run only the very first time the VM is booted, but that seems dangerous/non-trivial).

**Comment by paskino** [comment]
I think that is a good idea.
