### ISSUE TITLE
VB update

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#69]
Today (6th March, 2018), VB is suggesting updating to version 5.2.8. I assume this is not a good idea, better to stay at the same version used when the VM was created (5.2.6)?

**Comment by KrisThielemans** [comment]
we advice to use 5.2.6, but it is likely fine to use 5.2.8. if the difference in version is too large, we will have trouble.

Any volunteers to try?

**Comment by paskino** [comment]
I guess with 1.0 I'll use the latest stable virtual box.

**Comment by KrisThielemans** [comment]
using 5.2.8 at present
