### ISSUE TITLE
Naming of VM versions

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#70]
The filename of the downloaded VM is `SIRF_1.0.0-rc.1.ova` but, the name of the machine is `SIRF_1.0.0-rc.1_1` so there might be some confusion for users?

**Comment by KrisThielemans** [comment]
this will happen if you have imported the VM twice. The 2nd copy will have the _1 name. Is that the case for you?

**Comment by DANAJK** [comment]
Yes, it was imported a few weeks ago. If today’s version is the same code as a few weeks ago, that is OK, but if it is different, that’s a bit confusing.

--

**Comment by KrisThielemans** [comment]
today's version of the VM is still the same. `updateVM.sh` will still give you the same version, until we tag rc2.
