### ISSUE TITLE
VM disk size seems limited to 10Gb

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/CCPPETMR_VM#75]
I've stumbled upon a low disk on the VM while working at my conda experiment.

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           396M  6.1M  390M   2% /run
/dev/sda1       9.7G  9.4G  226M  98% /
tmpfs           2.0G  384K  2.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           396M   16K  396M   1% /run/user/112
tmpfs           396M   12K  396M   1% /run/user/1002
```

**Comment by paskino** [comment]
Yes the trick works. 

I guess the next VM will have that, then, or do I make a new one now?

**Comment by evgueni-ovtchinnikov** [comment]
@paskino: if it is not too difficult, and the risk to break something is negligible, i believe you should make a new one now

to be safe, add the link to the current one to previous VMs in Downloads as VM with SIRF 1.1.0

**Comment by paskino** [comment]
What HDD size?

**Comment by paskino** [comment]
For the current 1.1.1 version of the VM I run the manual steps described in the [link above](https://tuhrig.de/resizing-vagrant-box-disk-space/).

For a more standardised way I plan to try the script found here https://github.com/hashicorp/vagrant/issues/3567 or 
http://crysol.github.io/recipe/2015-11-17/vagrant-vdi-virtual-disk-for-virtualbox.html#.Wxf6QkgvxO8

**Comment by KrisThielemans** [comment]
I'd prefer not to muddy the waters and therefore NOT replace the current 1.1.1 VM with a new one. If we need this now, then I'd prefer if you'd upload a 2nd VM (saying it's 1.1.1 with extra disk space). If it all works fine, we could get rid of the older one of course

**Comment by KrisThielemans** [comment]
@paskino I think you've fixed this in the Ubuntu 18.04 upgrade?

**Comment by KrisThielemans** [comment]
@paskino, I'm sure this is fixed, but I cannot see where. Please confirm and then close.

**Comment by paskino** [comment]
yes, the bento box the VM is based on creates a [64Gb](https://github.com/chef/bento/blob/master/ubuntu/ubuntu-18.04-amd64.json#L296) disk by default.
