### ISSUE TITLE
write access to shared folder

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#76]
with current instructions in https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/INSTALL.md  on recent VBox, a shared folder doesn't have write permissions.

@DANAJK suggests adding `,dmode=777,fmode=666` to the mount command. `umask` doesn't help.

**Comment by casperdcl** [comment]
I'd suggest `umask` (for forcing permissions), `uid` and `gid` (to match host), for example

```
umask=007,uid=1000,gid=46
```

Note that for `docker`, the entrypoint for the container actually creates a new user with `uid`/`gid` matching the host if possible and sets file permissions https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/docker/entrypoint.sh

**Comment by KrisThielemans** [comment]
@DANAJK do we still have to do anything here? If not, close it.

**Comment by DANAJK** [comment]
I have a set-up that seems to work and I updated the instructions. Note it required running the id command in the VM and using the user and group id reported by that. This does not seem to be the same as suggested above.
