### ISSUE TITLE
current VM screen lock comes on too soon

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#80]
Screen lock comes on too soon and sirfuser does not appear to have permission to change time to lock.

**Comment by KrisThielemans** [comment]
actually, what the above does is make sure you don't have to type the password. the screensaver still comes on. could just increase the delay I guess.

**Comment by paskino** [comment]
By the way, I'm quite [surprised ](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/first_run.sh#L34)this is an issue at all. 
Maybe I forgot to run `first_run.sh`?

**Comment by KrisThielemans** [comment]
not sure how we could check if you ran it.
would this explain #78?

**Comment by paskino** [comment]
Possibly. I'll do that now and upload again. 
When you do too many things together...

**Comment by KrisThielemans** [comment]
not sure if it's worth uploading now? There's a few other VM issues that need sorting out as well. Depends on how much effort this is for you.

**Comment by paskino** [comment]
One obvious way to check if I'd run it is to see if the cursor is large. It is large in my VM. So I've run the `first_run.py` script.

**Comment by KrisThielemans** [comment]
yup. large in mine as well. Also a bunch of portuguese etc languages installed (but not UK English). I guess you'll have to create a new one from scratch and just check it yourself (did you put the virtualbox (attempted) fixes in?)

**Comment by KrisThielemans** [comment]
running `update_VGA.sh` myself seems to have fixed my VM. I've rebooted it about 6 times without trouble. hard to be sure of course.

can others please try the new VM, run `updateVGA.sh` and then use it for a while, restart etc. We could just tell users to run `update_VGA.sh` after installation.
