### ISSUE TITLE
README should refer to update_VGA.sh

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#81]
Our README gives explicit mount instructions etc for the VGA, but those don't necessarily work. Replace with calling `update_VGA.sh` (note that this doc is also somewhere else I believe, but that's fine).

**Comment by paskino** [comment]
closed with https://github.com/CCPPETMR/CCPPETMR_VM/commit/2d0173e04f326e21792fffa3f121312fe6a8edaf
