### ISSUE TITLE
UPDATE.sh not executable and fatal message

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#85]
UPDATE.sh in ~/devel/CCPPETMR_VM/scripts is rw, not rwx and so does not run.

After a chmod, it runs but I see this message go past:

> [ 91%] Built target STIR
> [ 92%] Performing update step for 'SIRF'
> fatal: ambiguous argument 'v1.1.0-rc.1': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> From https://github.com/CCPPETMR/SIRF
>    e6f6036..32bca43  SIRFReg    -> origin/SIRFReg
>    4030287..08bf0a6  devel      -> origin/devel
>    d4ddddf..243a2ea  master     -> origin/master
>  * [new tag]         v1.1.0-rc.1 -> v1.1.0-rc.1
> Previous HEAD position was d4ddddf... fixed a bug in test4.cpp (return 0 despite exception thrown)
> M	data
> M	examples/Python/MR/interactive/coil_combination.py
> HEAD is now at 243a2ea... fixed a bug in mr image read from file
> [ 93%] Performing configure step for 'SIRF'

**Comment by KrisThielemans** [comment]
I've fixed the permissions. @paskino, looks like you changed those in 54126d3a97e21e3ec47399afb84c8f4d248c1244. No idea how.

The error `fatal: ambiguous argument 'v1.1.0-rc.1': unknown revision or path not in the working tree.` seems a CMake ExternalPackage bug. However, luckily it all seems to be fine then. Can you check with `git status` in `~/devel/buildVM/sources/SIRF`?

We might want to update our cmake version at some point (not now...)

**Comment by KrisThielemans** [comment]
yes you did.

I go to linux, and do `chmod +x *.sh; git commit`

Here's [a post on how to fix it[(https://medium.com/@akash1233/change-file-permissions-when-working-with-git-repos-on-windows-ea22e34d5cee). However, if it changed it accidentally, 
it probably means your windows git isn't configured properly though. I'll let you google that...
