### ISSUE TITLE
UPDATE.sh doesn't work properly when it uses clone_or_pull

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#89]
this old function is used to update the SIRF-Exercises. However, it esssentially does
```
 git fetch
 git checkout master
```
This isn't enough, as the fetch still doesn't sync master with origin/master. 

A possibility would be to do 
```
git checkout origin/master
```
leaving in detached HEAD state.
It seems better to do
```
 git checkout master
 git pull
```
@casperdcl , @edo. ok?

**Comment by KrisThielemans** [comment]
this must have happened when we put the "gitref" stuff in. it should do what the name says, so let's fix it :-;.

thanks

**Comment by casperdcl** [comment]
I'd recommmend `git checkout master && git pull`, there may be a warning if local changes conflict though

**Comment by KrisThielemans** [comment]
ok. let's do that. local conflicts not to be flagged anyway. @paskino will make this change
