### ISSUE TITLE
Guest Additions

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/CCPPETMR_VM#9]
Turn off guest editions or enforce VirtualBox version number?

**Comment by KrisThielemans** [comment]
Our Vagrantfile uses
https://atlas.hashicorp.com/box-cutter/boxes/ubuntu1604
This has VirtualBox Guest Additions 5.1.10 installed. This will create problems on older VirtualBox (Evgueni experienced networking problems with VB 5.0.12).

We might have to remove the VGA:

     sudo /opt/VirtualBox/uninstall.sh

(or use a different box) and then reinstall it, possibly first requiring

    sudo apt-get install build-essential module-assistant;
    sudo m-a prepare

as [documented here](https://virtualboxes.org/doc/installing-guest-additions-on-ubuntu/). This could be done in the VagrantFile. We could then tell the user to install the VGA afresh.

When using vagrant itself as opposed to an exported VB, [vb-guest](https://github.com/dotless-de/vagrant-vbguest) seems to be popular.

**Comment by bathomas** [comment]
I know it's not a solution, but VB 5.0.12 is more than a year old and is getting security fixes only now. Is it wise to provide instructions to fix the appliance for an older version of VB, given that VB will prompt the user to upgrade? Presumably users might then encounter problems with Guest Additions mis-match if they were to upgrade having just fixed the machine.

**Comment by KrisThielemans** [comment]
sure. but PSMR machines has VB 5.0.40 which isn't so old. And whatever we do, we will nearly always have mismatched VB and VGA versions.

**Comment by bathomas** [comment]
What about a separate Bash script that removes the Guest additions, wgets the appropriate ISO (avoids problems with CDROM mounting), mounts the ISO (loop?) and installs?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DANAJK** [comment]
Using latest virtual box 5.1.22 r115126 (Qt5.6.2) on MacOS Sierra 10.12.5 and following the link on our Download page https://www.ccppetmr.ac.uk/downloads :


* No instructions obviously available for users. (Fortunately, I remembered the password). There is a paragraph on the downloads page that starts “Detailed instructions on set up and use of this image …” but this text implies it refers to the previous paragraph which is about an obsolete VM image  (so why is it listed if obsolete?) So, I just tried without instructions.

* Some message about Guest additions appeared but vanished in the VM.

* Took me a while to figure out how to get a terminal window.

* gadgetron started OK

* opened Spyder, chose fully_sampled_recon.py and pressed the green arrow to run. Get error message:
ImportError: No module named pGadgetron


David

**Comment by KrisThielemans** [comment]
I guess so. It would fail if the old VGA blocks network connection, but I guess starting off without VGA should prevent that.

But how would the bash script on the guest know what VB version the host is running? Can't be done I think. Better to provide a bash script that checks if the appropriate cdrom is 'inserted', and if not says what to do.

sad to see that the VB doc is just way too complicated for all this.

**Comment by bathomas** [comment]
```bash
sudo dmidecode | grep vboxVer | sed 's/.*_//'
```
Returns the VirtualBox version number for me.

**Comment by KrisThielemans** [comment]
indeed it does. amazing.

so what about this? if VGAiso is mounted, use that. Otherwise, use your trick to wget. I'll try that now.

Do we need to uninstall VGA first ourselves? I don't think so. The normal installer will attempt this. if that fails, we're out of luck anyway.

Do we need to install kernel modules as above, dkms (used to be ages ago) etc?
