### ISSUE TITLE
VM ships with Boost 1.58, master requires 1.64

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/CCPPETMR_VM#95]
Our VM ships with Boost 1.58, but we've moved our required version to 1.64. We should update our version of boost accordingly for the next version of the VM (presumably 2.0 when we do that officially).

**Comment by paskino** [comment]
With the plan to [upgrade the VM to Ubuntu 18.04](https://github.com/CCPPETMR/SIRF-SuperBuild/issues/146) this issue will be closed as system boost is [1.65](https://packages.ubuntu.com/bionic/libboost-all-dev).
